# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy app code
COPY . .

# Install FastAPI and Uvicorn
RUN pip install fastapi uvicorn



# Expose port
EXPOSE 8000

# Command to run server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
